# Generated by Django 5.0.7 on 2024-07-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='amount_expent',
            new_name='amount_earn',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='surname',
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, default='Hello', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, default='World', max_length=200, null=True),
        ),
    ]
